id: IF74A10FF
legacy_id: P008230
ocr_import_info:
  bdrc_scan_id: W1CZ885
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T23:05:10'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T19:38:57.726570+00:00'
last_modified: 2022-08-31 03:39:09.458001
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1CZ885
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1CZ885
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཆོས་དང་ཆོས་མ་ཡིན་པ་རྣམ་པར་དབྱེ་བའི་རབ་ཏུ་བྱེད་པ།
  author: འབྲི་གུང་དཔལ་འཛིན།
statistics:
  ocr_word_mean_confidence_index: 0.6439615946358657
  ocr_word_median_confidence_index: 0.6800000071525574
quality: null
bases:
  I1CZ2153:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ2153
      total_pages: 78
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1CZ2153.txt
    statistics:
      ocr_word_median_confidence_index: 0.6800000071525574
      ocr_word_mean_confidence_index: 0.6439615946358657
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
