id: IF74A10FF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T23:05:39+00:00'
last_modified: '2022-06-08T08:05:34.628795+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ885
  title: ཆོས་དང་ཆོས་མ་ཡིན་པ་རྣམ་པར་དབྱེ་བའི་རབ་ཏུ་བྱེད་པ་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    BBFE:
      image_group_id: I1CZ2153
      title: ''
      total_pages: 78
      order: 1
      base_file: BBFE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
