id: P008230
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ885
  title: ཆོས་དང་ཆོས་མ་ཡིན་པ་རྣམ་པར་དབྱེ་བའི་རབ་ཏུ་བྱེད་པ་
  author: ''
  volumes:
    2ad7f5545b564f808acf9cfb9d4b0963:
      image_group_id: I1CZ2153
      title: ''
      volume_number: 1
      total_pages: 78
